ilist = [10,20,30,40,50,60,70,80,90,100]
print('ilist:',ilist)
print('First element : ', ilist[0])
print('Fourth element : ', ilist[3])
print('ilist elements from 0 to 4 index : ',ilist[0:5])
print('3rd or -7th element : ', ilist[-7])
ilist.append(111)
print('ilist after append() : ', ilist)
print('index of 80:',ilist.index(80))
ilist.sort()
print('After sorting : ',ilist)
print("popped elements is : ",ilist.pop())
print('After pop()',ilist)
ilist.remove(80)
print('Afert removing 80:',ilist)